def print_board(board):
    for row in board:
        print(" | ".join(row))
        if row != board [-1] :
            print("---------")
def check_winner(board, player):#Проверяет, выиграл ли игрок
    for row in board:
        if all(cell == player for cell in row):
            return True
    for col in range(3):
        if all(board[row][col] == player for row in range(3)):
            return True
    if all(board[i][i] == player for i in range(3)):
        return True
    if all(board[i][2-i] == player for i in range(3)):
        return True
    return False

def is_full(board):#Проверяет, заполнено ли поле
    return all(cell != " " for row in board for cell in row)

def play_game(player_x, player_o):
    board = [[" " for _ in range(3)] for _ in range(3)]
    current_player = "X"
    print("Добро пожаловать в игру Крестики‑нолики")
    print_board(board)
    while True:
        try:
            current_name = player_x if current_player == "X" else player_o
            print(f"Ход игрока {current_name} ({current_player}). Введите строку и столбец (1–3):")
            row = int(input("Строка (1–3): ")) - 1
            col = int(input("Столбец (1–3): ")) - 1
            if not (0 <= row < 3 and 0 <= col < 3):
                print("Ошибка: введите числа от 1 до 3.")
                continue
            if board[row][col] != " ":
                print("Эта клетка уже занята!Повторите ввод")
                continue
            board[row][col] = current_player
            print_board(board)
            if check_winner(board, current_player):
                winner = player_x if current_player == "X" else player_o
                print(f"Игрок {winner} ({current_player}) победил! Поздравляем!")
                return ask_restart(player_x, player_o)
            if is_full(board):
                print("Ничья! Поле заполнено.")
                return ask_restart(player_x, player_o)
            current_player = "O" if current_player == "X" else "X"
        except ValueError:
            print("Ошибка: введите число.")
        except KeyboardInterrupt:
            print("Игра прервана.")
            return
def ask_restart(player_x, player_o):#хочет ли пользователь сыграть ещё раз
    while True:
        answer = input("Хотите сыграть ещё раз? (да/нет): ").strip().lower()
        if answer in ("да", "lf"):
            return play_game(player_x, player_o)
        elif answer in ("нет", "ytn"):
            print("Спасибо за игру!")
            return
        else:
            print("Пожалуйста, введите 'да' или 'нет'.")
if __name__ == "__main__":
    player_x = input("Введите имя первого игрока: ")
    player_o = input("Введите имя второго игрока: ")
    play_game(player_x, player_o)
